# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mconnect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mconnect
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  target 'mconnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mconnect-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mconnect-tvOS

  target 'mconnect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
